awsStack:
  title: dinghy.dev Demo Sites
  s3Backend: true
  regionalLogBucket: true
  globalLogBucket: true
s3Bucket:
  loggingEnabled: true
awsProvider:
  region: eu-west-1
sites:
  cloudfront-site-demo.dinghy.dev:
    origins:
      site_root:
        target: 's3://dinghy-dev-demo-sites-origin'
    redirectFromNames:
      - '*.cloudfront-site-demo.dinghy.dev'
    certVersions:
      - '20260104'
    custom_error_response:
      - error_code: 403
        response_code: 404
        error_caching_min_ttl: 3600
        response_page_path: /404.html
