name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dinghydev/setup-dinghy@v1
      - run: dinghy check
      - run: dinghy render
  diff:
    runs-on: ubuntu-latest
    needs: verify
    outputs:
      pending_changes: ${{ env.DINGHY_TF_DIFF_PENDING_CHANGES }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEPLOY_REGION }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
      - uses: dinghydev/setup-dinghy@v1
        with:
          prepare-images: release,tf
      - run: dinghy tf diff
      - uses: actions/upload-artifact@v6
        if: env.DINGHY_TF_DIFF_PENDING_CHANGES == 'true'
        with:
          name: dinghy-output
          path: output/
  deploy:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.pending_changes == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEPLOY_REGION }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
      - uses: dinghydev/setup-dinghy@v1
        with:
          prepare-images: release,tf
      - name: Download Dinghy Output
        uses: actions/download-artifact@v6
        with:
          name: dinghy-output
          path: output/
      - run: dinghy tf deploy
